-- Server-authoritative product roles, Premium access, coupons and releases.
-- Existing is_superuser rows are migrated once; email addresses are never an
-- authorization dependency.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user';

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check CHECK (role IN ('user', 'superuser'));

UPDATE public.profiles
SET role = 'superuser'
WHERE is_superuser = true AND role <> 'superuser';

CREATE OR REPLACE FUNCTION public.is_superuser(check_user_id uuid DEFAULT auth.uid())
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = check_user_id AND role = 'superuser'
  );
$$;

REVOKE ALL ON FUNCTION public.is_superuser(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_superuser(uuid) TO authenticated;

CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  plan text NOT NULL DEFAULT 'standard' CHECK (plan IN ('standard', 'premium')),
  status text NOT NULL DEFAULT 'inactive' CHECK (status IN ('inactive', 'active', 'trial', 'expired', 'cancelled', 'granted')),
  source text NOT NULL DEFAULT 'none' CHECK (source IN ('none', 'coupon', 'admin', 'store', 'migration')),
  premium_started_at timestamptz,
  premium_expires_at timestamptz,
  permanent boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.premium_coupons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL,
  duration_days integer,
  permanent boolean NOT NULL DEFAULT false,
  max_uses integer,
  expires_at timestamptz,
  active boolean NOT NULL DEFAULT true,
  one_per_account boolean NOT NULL DEFAULT true,
  note text,
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT premium_coupons_code_format CHECK (code ~ '^[A-Z0-9][A-Z0-9_-]{3,31}$'),
  CONSTRAINT premium_coupons_duration CHECK ((permanent AND duration_days IS NULL) OR (NOT permanent AND duration_days BETWEEN 1 AND 3650)),
  CONSTRAINT premium_coupons_max_uses CHECK (max_uses IS NULL OR max_uses > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS premium_coupons_code_unique
ON public.premium_coupons (upper(code));

CREATE TABLE IF NOT EXISTS public.coupon_redemptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  coupon_id uuid NOT NULL REFERENCES public.premium_coupons(id),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  redeemed_at timestamptz NOT NULL DEFAULT now(),
  premium_from timestamptz NOT NULL,
  premium_until timestamptz,
  UNIQUE (coupon_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.app_releases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL DEFAULT 'android' CHECK (platform IN ('android', 'ios')),
  version text NOT NULL,
  build_number integer NOT NULL,
  runtime_version text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  update_level text NOT NULL DEFAULT 'optional' CHECK (update_level IN ('optional', 'recommended', 'required')),
  minimum_native_version text,
  store_url text,
  published boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (platform, version, build_number)
);

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid NOT NULL REFERENCES auth.users(id),
  action text NOT NULL,
  target_user_id uuid REFERENCES auth.users(id),
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premium_coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS subscriptions_select_own ON public.user_subscriptions;
CREATE POLICY subscriptions_select_own ON public.user_subscriptions
FOR SELECT USING (user_id = auth.uid() OR public.is_superuser());

DROP POLICY IF EXISTS coupons_admin_read ON public.premium_coupons;
CREATE POLICY coupons_admin_read ON public.premium_coupons
FOR SELECT USING (public.is_superuser());

DROP POLICY IF EXISTS redemptions_select_own ON public.coupon_redemptions;
CREATE POLICY redemptions_select_own ON public.coupon_redemptions
FOR SELECT USING (user_id = auth.uid() OR public.is_superuser());

DROP POLICY IF EXISTS releases_published_read ON public.app_releases;
CREATE POLICY releases_published_read ON public.app_releases
FOR SELECT USING (published OR public.is_superuser());

DROP POLICY IF EXISTS audit_admin_read ON public.admin_audit_log;
CREATE POLICY audit_admin_read ON public.admin_audit_log
FOR SELECT USING (public.is_superuser());

DROP TRIGGER IF EXISTS set_updated_at ON public.user_subscriptions;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.user_subscriptions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.premium_coupons;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.premium_coupons
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at ON public.app_releases;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.app_releases
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.get_my_product_access()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_role text;
  v_sub public.user_subscriptions%ROWTYPE;
  v_premium boolean;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'authentication_required'; END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = v_user_id;
  SELECT * INTO v_sub FROM public.user_subscriptions WHERE user_id = v_user_id;
  v_premium := v_role = 'superuser' OR (
    v_sub.plan = 'premium' AND v_sub.status IN ('active', 'trial', 'granted')
    AND (v_sub.permanent OR v_sub.premium_expires_at > now())
  );
  RETURN jsonb_build_object(
    'role', coalesce(v_role, 'user'),
    'plan', CASE WHEN v_premium THEN 'premium' ELSE 'standard' END,
    'isPremium', v_premium,
    'isSuperuser', v_role = 'superuser',
    'premiumExpiresAt', CASE WHEN v_role = 'superuser' OR v_sub.permanent THEN NULL ELSE v_sub.premium_expires_at END,
    'source', CASE WHEN v_role = 'superuser' THEN 'superuser' ELSE coalesce(v_sub.source, 'none') END
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.redeem_premium_coupon(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_coupon public.premium_coupons%ROWTYPE;
  v_existing_until timestamptz;
  v_from timestamptz;
  v_until timestamptz;
  v_uses bigint;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'authentication_required'; END IF;
  SELECT * INTO v_coupon FROM public.premium_coupons
  WHERE code = upper(trim(p_code)) FOR UPDATE;
  IF NOT FOUND OR NOT v_coupon.active THEN RAISE EXCEPTION 'coupon_invalid'; END IF;
  IF v_coupon.expires_at IS NOT NULL AND v_coupon.expires_at <= now() THEN RAISE EXCEPTION 'coupon_expired'; END IF;
  IF v_coupon.one_per_account AND EXISTS (
    SELECT 1 FROM public.coupon_redemptions WHERE coupon_id = v_coupon.id AND user_id = v_user_id
  ) THEN RAISE EXCEPTION 'coupon_already_redeemed'; END IF;
  SELECT count(*) INTO v_uses FROM public.coupon_redemptions WHERE coupon_id = v_coupon.id;
  IF v_coupon.max_uses IS NOT NULL AND v_uses >= v_coupon.max_uses THEN RAISE EXCEPTION 'coupon_limit_reached'; END IF;
  SELECT premium_expires_at INTO v_existing_until FROM public.user_subscriptions
  WHERE user_id = v_user_id AND plan = 'premium' AND status IN ('active', 'trial', 'granted');
  v_from := greatest(now(), coalesce(v_existing_until, now()));
  v_until := CASE WHEN v_coupon.permanent THEN NULL ELSE v_from + make_interval(days => v_coupon.duration_days) END;
  INSERT INTO public.coupon_redemptions(coupon_id, user_id, premium_from, premium_until)
  VALUES (v_coupon.id, v_user_id, v_from, v_until);
  INSERT INTO public.user_subscriptions(user_id, plan, status, source, premium_started_at, premium_expires_at, permanent)
  VALUES (v_user_id, 'premium', 'active', 'coupon', now(), v_until, v_coupon.permanent)
  ON CONFLICT (user_id) DO UPDATE SET
    plan = 'premium', status = 'active', source = 'coupon',
    premium_started_at = coalesce(user_subscriptions.premium_started_at, now()),
    premium_expires_at = CASE WHEN user_subscriptions.permanent THEN user_subscriptions.premium_expires_at ELSE excluded.premium_expires_at END,
    permanent = user_subscriptions.permanent OR excluded.permanent;
  RETURN public.get_my_product_access();
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_create_coupon(
  p_code text, p_duration_days integer DEFAULT 30, p_max_uses integer DEFAULT NULL,
  p_expires_at timestamptz DEFAULT NULL, p_note text DEFAULT NULL, p_permanent boolean DEFAULT false
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_id uuid;
BEGIN
  IF NOT public.is_superuser() THEN RAISE EXCEPTION 'admin_required'; END IF;
  INSERT INTO public.premium_coupons(code, duration_days, max_uses, expires_at, note, permanent, created_by)
  VALUES (upper(trim(p_code)), CASE WHEN p_permanent THEN NULL ELSE p_duration_days END, p_max_uses, p_expires_at, nullif(trim(p_note), ''), p_permanent, auth.uid())
  RETURNING id INTO v_id;
  INSERT INTO public.admin_audit_log(actor_user_id, action, entity_id, metadata)
  VALUES (auth.uid(), 'coupon.created', v_id::text, jsonb_build_object('code', upper(trim(p_code)), 'durationDays', p_duration_days, 'maxUses', p_max_uses, 'permanent', p_permanent));
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_coupon_active(p_coupon_id uuid, p_active boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_superuser() THEN RAISE EXCEPTION 'admin_required'; END IF;
  UPDATE public.premium_coupons SET active = p_active WHERE id = p_coupon_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'coupon_not_found'; END IF;
  INSERT INTO public.admin_audit_log(actor_user_id, action, entity_id, metadata)
  VALUES (auth.uid(), CASE WHEN p_active THEN 'coupon.enabled' ELSE 'coupon.disabled' END, p_coupon_id::text, '{}'::jsonb);
END;
$$;

REVOKE ALL ON FUNCTION public.get_my_product_access() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_premium_coupon(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_create_coupon(text, integer, integer, timestamptz, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_coupon_active(uuid, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_product_access() TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_premium_coupon(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_coupon(text, integer, integer, timestamptz, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_coupon_active(uuid, boolean) TO authenticated;

REVOKE ALL ON public.user_subscriptions, public.premium_coupons, public.coupon_redemptions, public.app_releases, public.admin_audit_log FROM anon;
GRANT SELECT ON public.user_subscriptions, public.coupon_redemptions, public.app_releases TO authenticated;
GRANT SELECT ON public.premium_coupons, public.admin_audit_log TO authenticated;

CREATE INDEX IF NOT EXISTS coupon_redemptions_coupon_idx ON public.coupon_redemptions(coupon_id, redeemed_at);
CREATE INDEX IF NOT EXISTS app_releases_published_idx ON public.app_releases(platform, published, published_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_created_idx ON public.admin_audit_log(created_at DESC);
